plugins {
    alias(libs.plugins.android.library)
}
apply from: "../common.gradle"

android {
    namespace "de.danoeh.antennapod.event"

    defaultConfig {
        missingDimensionStrategy "market", "play"
    }
}

dependencies {
    implementation project(':model')
    implementation libs.androidx.core

    annotationProcessor libs.androidx.annotation

    testImplementation project(':net:download:service-interface')
    testImplementation project(':storage:database')
    testImplementation project(':storage:preferences')
    testImplementation project(':net:sync:service-interface')
    testImplementation libs.junit
    testImplementation libs.eventbus
    testImplementation libs.androidx.test.core
    testImplementation libs.robolectric
}
